// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl5_wgNONKJ4KNzL8UdlAG8kxcyUo_rao',
    appId: '1:1085028424107:web:52759bf969e6047765daee',
    messagingSenderId: '1085028424107',
    projectId: 'starsync-8bf37',
    authDomain: 'starsync-8bf37.firebaseapp.com',
    storageBucket: 'starsync-8bf37.appspot.com',
    measurementId: 'G-HPMY379S5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFkKU82B_GyQGtCKBjEmNvbgibLDy0Xso',
    appId: '1:1085028424107:android:fada18b4f2810fe265daee',
    messagingSenderId: '1085028424107',
    projectId: 'starsync-8bf37',
    storageBucket: 'starsync-8bf37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwHs0bc40-c-L6Aosj2iDcMDejqM1yEVc',
    appId: '1:1085028424107:ios:7c9c9ecc1e17a5c165daee',
    messagingSenderId: '1085028424107',
    projectId: 'starsync-8bf37',
    storageBucket: 'starsync-8bf37.appspot.com',
    iosBundleId: 'com.akshaykotish.starsync.starsyncapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwHs0bc40-c-L6Aosj2iDcMDejqM1yEVc',
    appId: '1:1085028424107:ios:7c9c9ecc1e17a5c165daee',
    messagingSenderId: '1085028424107',
    projectId: 'starsync-8bf37',
    storageBucket: 'starsync-8bf37.appspot.com',
    iosBundleId: 'com.akshaykotish.starsync.starsyncapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl5_wgNONKJ4KNzL8UdlAG8kxcyUo_rao',
    appId: '1:1085028424107:web:729b9b99a0694e4865daee',
    messagingSenderId: '1085028424107',
    projectId: 'starsync-8bf37',
    authDomain: 'starsync-8bf37.firebaseapp.com',
    storageBucket: 'starsync-8bf37.appspot.com',
    measurementId: 'G-JD9CRMV2Y8',
  );
}
